//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.09 at 10:49:13 PM WEST 
//

import java.util.ArrayList;
import java.util.List;

public class Studios {

    protected List<String> studio;

    public List<String> getStudio() {
        if (studio == null) {
        	studio = new ArrayList<String>();
        }
        return this.studio;
    }

}
